### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by di48l069** [Arcidev/Arci.Networking#1]
Hello @Arcidev  epic app! do you have an example small console netcore **chat** using Arci.Networking?

**Comment by Arcidev** [comment]
Hi, I can try to provide one today or tommorow if I'll have some time. Right now you can check client side of a little card game I made before https://github.com/Arcidev/Card-Game (its .NET 4.6.1 but there will be probably no difference there) it also got a chat there.

I'll let you know when I'll finish one

**Comment by di48l069** [comment]
Thank you means alot please do respond  to this issue once you done :) doesnt have to be anything fancy just a normal chat client with server :)

**Comment by di48l069** [comment]
Quick question @Arcidev will the server side on the example chat client console be c# or c++ because I'm not familiar with c++ haha

**Comment by Arcidev** [comment]
C# for both (its easier that way)

**Comment by di48l069** [comment]
thats amazing

________________________________

**Comment by di48l069** [comment]
Hello @Arcidev did you have any chance whipping up a example?

**Comment by Arcidev** [comment]
@di48l069 Hi, I've got the server part done, but still need to finish client part. Didn't have much time lately as I got a lot of work to do plus I have to finish my diploma thesis. I hope I'll be done with it this week

**Comment by di48l069** [comment]
@Arcidev no stress thank you for this.

**Comment by Arcidev** [comment]
Here is the sample. Its really just basic chaty. The only thing you need to do is build it and then run it with dotnet command (dotnet client.dll or dotnet server.dll). First run the server (there is not implemented checking if server is online so client will crash if not) then run as many clients as you want. You will be prompted to write your name and then you can start chatting.

[ChatSample.zip](https://github.com/Arcidev/Arci.Networking/files/981948/ChatSample.zip)

**Comment by di48l069** [comment]
Thanks bud I really appreciate this @Arcidev I will be creating a repro on this eventually will add ability for a user to register account.

**Comment by di48l069** [comment]
@Arcidev i noticed there is a shared projected containing RSA key, how would generate that info? Does it need to be changed?

**Comment by Arcidev** [comment]
@di48l069 I've made it with OpenSSL (https://rietta.com/blog/2012/01/27/openssl-generating-rsa-key-from-command/). Basically you do not even need to use it. I've just gave you example with some security of those messages. If you want to protect users and their messages you should change it and not to use that one (Private Key is used on server, Public Key on client... Main thing is not to share your private key at all)

**Comment by Arcidev** [comment]
@di48l069 using [this](http://www.dsm.fordham.edu/~mathai/openssl.html) should generate you all the data that are in the shared project

**Comment by di48l069** [comment]
Legend thank you @Arcidev

**Comment by di48l069** [comment]
@Arcidev I have added you to the chat server you made it will be cool if people can actually make something of it :octocat:
