### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by LostSoulfly** [Arcidev/Arci.Networking#2]
I'm trying to create a client\server that generates an RSA keypair on the first run (or on demand), exports to a file, and then sends the public key to the client to initiate AES key exchange. And then the client would store the public key for later use. 

However, I'm not sure which RSAParameters to send to the client in order to initialize RSAEncryptor.

Is this a safe way of authenticating? Should I handle it differently?

Thanks for your time.

Edit: Here's my RSAFactory function:

```
public RSAFactory()
        {
            using (var rsa = new RSACryptoServiceProvider(1024))
            {
                try
                {
                    RSAParameters _rsaParameters;
                    _rsaParameters = rsa.ExportParameters(true);
                    this.modulus = _rsaParameters.Modulus;
                    this.exponent = _rsaParameters.Exponent;
                    this.d = _rsaParameters.D;
                    this.p = _rsaParameters.P;
                    this.q = _rsaParameters.Q;
                    this.dp = _rsaParameters.DP;
                    this.dq = _rsaParameters.DQ;
                    this.inverseQ = _rsaParameters.InverseQ;
                }
                finally
                {
                    rsa.PersistKeyInCsp = false;
                    rsa.Dispose();
                }
            }
        }
```

**Comment by Arcidev** [comment]
For the encryption with the RSA public key only Modulus and the Exponent are required and then just initialized it with that like this.

```
var param = new RSAParameters { Exponent = publicExponent, Modulus = modulus };
var rsa = RSA.Create();
rsa.ImportParameters(param);
```

It's pretty common use that the server will send the public part of the key, the client will create AES key, encrypts it with RSA public key and sends it back to the server which will decrypt it with his private key

**Comment by LostSoulFly** [comment]
Thanks, that was a big help. [Here's what I've got so far for RSAFactory](https://gist.github.com/LostSoulFly/618edb9d5b8774f072c8f177f84c3c03).

I use RSAParametersSerializable from a StackExchange answer to allow serializing to JSON. I might work on exporting to a .pem or something later, but this is good enough for now.

Thanks!

**Comment by Arcidev** [comment]
Looks good to me, you can leave it in jSon with .pem files you'll probably have to convert it to that format and back. Within .NET it's mostly serialized to xml but that does not really matter in the end it's the same.
